#NoEnv  ; Recommended for performance and compatibility with future AutoHotkey releases.
; #Warn  ; Enable warnings to assist with detecting common errors.
SendMode Input  ; Recommended for new scripts due to its superior speed and reliability.
SetWorkingDir %A_ScriptDir%  ; Ensures a consistent starting directory.
:c:\Alpha::Α
:c:\Beta::Β
:c:\Gamma::Γ
:c:\Delta::Δ
:c:\Epsilon::Ε
:c:Zeta::Ζ
:c:\Eta::Η
:c:\Theta::Θ
:c:\Iota::Ι
:c:\Kappa::Κ
:c:\Lambda::Λ
:c:\Mu::Μ
:c:\Nu::Ν
:c:\Xi::Ξ
:c:\Omikron::Ο
:c:\Pi::Π
:c:\Rho::Ρ
:c:\Sigma::Σ
:c:\Tau::Τ
:c:\Upsilon::Υ
:c:\Phi::Φ
:c:\Chi::Χ
:c:\Psi::Ψ
:c:\Omega::Ω
::\alpha::α
::\beta::β
::\gamma::γ
::\delta::δ
::\epsilon::ε
::\zeta::ζ
::\êta::η
::\thêta::θ
::\iota::ι
::\kappa::κ
::\lambda::λ
::\mu::μ
::\nu::ν
::\xi::ξ
::\omikron::ο
::\pi::π
::\rho::ρ
::\sigma::σ
::\tau::τ
::\upsilon::υ
::\phi::φ
::\chi::χ
::\psi::ψ
::\omega::ω
:c:\Alpha::Α
:c:\Beta::Β
:c:\Gamma::Γ
:c:\Delta::ΔⒷⓤⓑⓑⓛⓔ
:c:\Epsilon::Ε
:c:Zeta::Ζ
:c:\Eta::Η
:c:\Theta::Θ
:c:\Iota::Ι
:c:\Kappa::Κ
:c:\Lambda::Λ
:c:\Mu::Μ
:c:\Nu::Ν
:c:\Xi::Ξ
:c:\Omikron::Ο
:c:\Pi::Π
:c:\Rho::Ρ
:c:\Sigma::Σ
:c:\Tau::Τ
:c:\Upsilon::Υ
:c:\Phi::Φ
:c:\Chi::Χ
:c:\Psi::Ψ
:c:\Omega::Ω
::\alpha::α
::\beta::β
::\gamma::γ
::\delta::δ
::\epsilon::ε
::\zeta::ζ
::\êta::η
::\thêta::θ
::\iota::ι
::\kappa::κ
::\lambda::λ
::\mu::μ
::\nu::ν
::\xi::ξ
::\omikron::ο
::\pi::π
::\rho::ρ
::\sigma::σ
::\tau::τ
::\upsilon::υ
::\phi::φ
::\chi::χ
::\psi::ψ
::\omega::ω




